; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/madhephaestus/ESP32Servo

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
board_build.mcu = esp32
board_build.f_cpu = 240000000L
lib_deps = 
	ppedro74/SerialCommands@^2.2.0
	madhephaestus/ESP32Servo@^3.1.3
	kroimon/SerialCommand@0.0.0-alpha+sha.76ebd2d60e

[env:esp12e_ota]
extends = core
upload_protocol = espota
upload_port = 192.168.4.1  ; IP-адрес вашего устройства
monitor_speed = 115200
